In [3]:
import pandas as pd
from sqlalchemy import create_engine

# Replace with your database connection details
engine = create_engine('postgresql://postgres:mustafabohra@localhost:5432/maimoon traders')

In [75]:
query = 'SELECT * FROM mainapp_customers_order_from_website'  # Replace with your actual table name
df = pd.read_sql(query, engine)
df

,order_number,customer_name,customer_email,customer_phone,address,pin_code,total_amount,created_at,is_paid,order_id,payment_id,is_accepted,user_name
0,50,Mustafa,mustafa.bohra20@vit.edu,9699596739,abc,411048,1.0,2024-07-18 13:35:59.425680+00:00,True,order_Oa76j529ZmJLN6,pay_Oa768MPdfWEje8,True,None
1,48,Mustafa Nahar,naharmustafa7@gmail.com,9699596739,abc,411048,15.0,2024-07-18 13:17:40.236221+00:00,True,order_Oa6nNH0R9wRHkg,pay_Oa6l12kP7qqcYO,True,None
2,49,mustu,naharmustafa7@gmail.com,9116426352,abc,411048,1.0,2024-07-18 13:22:22.207712+00:00,True,order_Oa6sL4t5tAzDeh,pay_Oa6rXE9l22nFQ4,True,None
3,58,Mustafa Antri,mustafaantriwala@gmail.com,9116426352,camp pune,411048,3.5,2024-07-20 12:26:48.982093+00:00,True,order_OaszzWbHD87WlK,pay_Oasxfb47SoXUqn,True,None
4,59,Mustafa Nahar,mustafa.bohra20@vit.edu,9699596739,abcdef,411048,5.0,2024-07-22 07:25:34.175853+00:00,True,order_Obaw0WpMQQpp0L,pay_Obatfot7k8pv2c,False,None
5,60,moiz,naharmustafa786@gmail.com,9699596739,abc,145202,1.0,2024-07-22 07:33:18.147646+00:00,True,order_Obb4Axt00FeAYq,pay_Obb1soZnpnLjul,False,None
6,61,mustu,mustafa.bohra20@vit.edu,9699596739,abc,411048,1.0,2024-07-23 08:21:01.682905+00:00,True,order_Oc0PhbE3MEbAPx,pay_Oc0NNdcK6KXRfF,False,dummy_profile_testing@gmail.com
7,44,zainab Nahar,naharmustafa7@gmail.com,9636268727,pune,411048,2.0,2024-07-06 07:16:59.606044+00:00,True,order_OVGF1RjxmVnP7k,pay_OVGCgz3hyeVjM4,True,None
8,45,Mubina Nahar,naharmustafa786@gmail.com,9116426352,402 Kondhwa,411048,2.0,2024-07-07 08:51:41.667985+00:00,True,order_OVgOAevt5329sy,pay_OVgLqn4Knl2vSZ,True,None
9,46,Moiz Lalji,naharmustafa786@gmail.com,9116426352,abc,314001,1.0,2024-07-07 17:10:22.792382+00:00,True,order_OVoswwS41EKVpe,pay_OVoqdW74KAmwRu,True,None
10,47,Huzaifa Mamji,naharmustafa7@gmail.com,9699596739,kondhwa pune,411048,1.0,2024-07-18 13:00:03.686612+00:00,True,order_Oa6Ulzhygu0jSa,pay_Oa6SSeU1cnEmqD,True,None
11,52,Mustafa Nahar,mustafa.bohra20@vit.edu,9116426352,abc,411048,1.0,2024-07-18 13:46:10.495307+00:00,True,order_Oa7HU6FPMgnvzW,pay_Oa7H2UiveZrc4X,True,None
12,51,Mustafa Nahar,mustafa.bohra20@vit.edu,9116426352,abc,314001,1.0,2024-07-18 13:43:22.477734+00:00,True,order_Oa7EWiuitLwVWj,pay_Oa7E5UMYwjpyA2,True,None
13,53,suresh,naharmustafa786@gmail.com,9699596739,dungarpur,314001,5.0,2024-07-18 15:51:09.698304+00:00,True,order_Oa9PbNHL6AGLye,pay_Oa9P3TccyQtwik,True,None
14,57,Mustafa testing,naharmustafa7@gmail.com,9699596739,abc kondhwa chowk,411048,7.0,2024-07-20 08:02:13.558840+00:00,True,order_OaoUUR7LglUD6V,pay_OaoSCyEDe2iCIr,False,None
15,56,mustu,naharmustafa7@gmail.com,9699596739,abc,314001,9.0,2024-07-18 18:17:58.371470+00:00,True,order_OaBugOK95Axc32,pay_OaBsLBPdChRGgw,True,None
16,55,Mubina Nahar Wala,naharmustafa7@gmail.com,9699596739,Dungarpur,314001,20.0,2024-07-18 18:14:26.160891+00:00,True,order_OaBqwoBs1UcNGz,pay_OaBodIGJem85Ee,True,None
17,54,Mustafa Nahar 1,mustafa.bohra20@vit.edu,9116426352,abc,411048,1.0,2024-07-18 16:00:29.677183+00:00,True,order_Oa9ZSdIhsQF5o4,pay_Oa9Z5CvzTJEqIH,True,None

In [76]:
df['created_at'] = pd.to_datetime(df['created_at'], format="%Y-%m-%d").dt.date

df

,order_number,customer_name,customer_email,customer_phone,address,pin_code,total_amount,created_at,is_paid,order_id,payment_id,is_accepted,user_name
0,50,Mustafa,mustafa.bohra20@vit.edu,9699596739,abc,411048,1.0,2024-07-18,True,order_Oa76j529ZmJLN6,pay_Oa768MPdfWEje8,True,None
1,48,Mustafa Nahar,naharmustafa7@gmail.com,9699596739,abc,411048,15.0,2024-07-18,True,order_Oa6nNH0R9wRHkg,pay_Oa6l12kP7qqcYO,True,None
2,49,mustu,naharmustafa7@gmail.com,9116426352,abc,411048,1.0,2024-07-18,True,order_Oa6sL4t5tAzDeh,pay_Oa6rXE9l22nFQ4,True,None
3,58,Mustafa Antri,mustafaantriwala@gmail.com,9116426352,camp pune,411048,3.5,2024-07-20,True,order_OaszzWbHD87WlK,pay_Oasxfb47SoXUqn,True,None
4,59,Mustafa Nahar,mustafa.bohra20@vit.edu,9699596739,abcdef,411048,5.0,2024-07-22,True,order_Obaw0WpMQQpp0L,pay_Obatfot7k8pv2c,False,None
5,60,moiz,naharmustafa786@gmail.com,9699596739,abc,145202,1.0,2024-07-22,True,order_Obb4Axt00FeAYq,pay_Obb1soZnpnLjul,False,None
6,61,mustu,mustafa.bohra20@vit.edu,9699596739,abc,411048,1.0,2024-07-23,True,order_Oc0PhbE3MEbAPx,pay_Oc0NNdcK6KXRfF,False,dummy_profile_testing@gmail.com
7,44,zainab Nahar,naharmustafa7@gmail.com,9636268727,pune,411048,2.0,2024-07-06,True,order_OVGF1RjxmVnP7k,pay_OVGCgz3hyeVjM4,True,None
8,45,Mubina Nahar,naharmustafa786@gmail.com,9116426352,402 Kondhwa,411048,2.0,2024-07-07,True,order_OVgOAevt5329sy,pay_OVgLqn4Knl2vSZ,True,None
9,46,Moiz Lalji,naharmustafa786@gmail.com,9116426352,abc,314001,1.0,2024-07-07,True,order_OVoswwS41EKVpe,pay_OVoqdW74KAmwRu,True,None
10,47,Huzaifa Mamji,naharmustafa7@gmail.com,9699596739,kondhwa pune,411048,1.0,2024-07-18,True,order_Oa6Ulzhygu0jSa,pay_Oa6SSeU1cnEmqD,True,None
11,52,Mustafa Nahar,mustafa.bohra20@vit.edu,9116426352,abc,411048,1.0,2024-07-18,True,order_Oa7HU6FPMgnvzW,pay_Oa7H2UiveZrc4X,True,None
12,51,Mustafa Nahar,mustafa.bohra20@vit.edu,9116426352,abc,314001,1.0,2024-07-18,True,order_Oa7EWiuitLwVWj,pay_Oa7E5UMYwjpyA2,True,None
13,53,suresh,naharmustafa786@gmail.com,9699596739,dungarpur,314001,5.0,2024-07-18,True,order_Oa9PbNHL6AGLye,pay_Oa9P3TccyQtwik,True,None
14,57,Mustafa testing,naharmustafa7@gmail.com,9699596739,abc kondhwa chowk,411048,7.0,2024-07-20,True,order_OaoUUR7LglUD6V,pay_OaoSCyEDe2iCIr,False,None
15,56,mustu,naharmustafa7@gmail.com,9699596739,abc,314001,9.0,2024-07-18,True,order_OaBugOK95Axc32,pay_OaBsLBPdChRGgw,True,None
16,55,Mubina Nahar Wala,naharmustafa7@gmail.com,9699596739,Dungarpur,314001,20.0,2024-07-18,True,order_OaBqwoBs1UcNGz,pay_OaBodIGJem85Ee,True,None
17,54,Mustafa Nahar 1,mustafa.bohra20@vit.edu,9116426352,abc,411048,1.0,2024-07-18,True,order_Oa9ZSdIhsQF5o4,pay_Oa9Z5CvzTJEqIH,True,None

In [77]:
# Preprocessing
df['created_at'] = pd.to_datetime(df['created_at'])  # Convert date column to datetime
df = df.set_index('created_at')

# Feature engineering
df['day_of_week'] = df.index.dayofweek
df['month'] = df.index.month
df['quarter'] = df.index.quarter

df

,order_number,customer_name,customer_email,customer_phone,address,pin_code,total_amount,is_paid,order_id,payment_id,is_accepted,user_name,day_of_week,month,quarter
created_at,,,,,,,,,,,,,,,
2024-07-18,50,Mustafa,mustafa.bohra20@vit.edu,9699596739,abc,411048,1.0,True,order_Oa76j529ZmJLN6,pay_Oa768MPdfWEje8,True,None,3,7,3
2024-07-18,48,Mustafa Nahar,naharmustafa7@gmail.com,9699596739,abc,411048,15.0,True,order_Oa6nNH0R9wRHkg,pay_Oa6l12kP7qqcYO,True,None,3,7,3
2024-07-18,49,mustu,naharmustafa7@gmail.com,9116426352,abc,411048,1.0,True,order_Oa6sL4t5tAzDeh,pay_Oa6rXE9l22nFQ4,True,None,3,7,3
2024-07-20,58,Mustafa Antri,mustafaantriwala@gmail.com,9116426352,camp pune,411048,3.5,True,order_OaszzWbHD87WlK,pay_Oasxfb47SoXUqn,True,None,5,7,3
2024-07-22,59,Mustafa Nahar,mustafa.bohra20@vit.edu,9699596739,abcdef,411048,5.0,True,order_Obaw0WpMQQpp0L,pay_Obatfot7k8pv2c,False,None,0,7,3
2024-07-22,60,moiz,naharmustafa786@gmail.com,9699596739,abc,145202,1.0,True,order_Obb4Axt00FeAYq,pay_Obb1soZnpnLjul,False,None,0,7,3
2024-07-23,61,mustu,mustafa.bohra20@vit.edu,9699596739,abc,411048,1.0,True,order_Oc0PhbE3MEbAPx,pay_Oc0NNdcK6KXRfF,False,dummy_profile_testing@gmail.com,1,7,3
2024-07-06,44,zainab Nahar,naharmustafa7@gmail.com,9636268727,pune,411048,2.0,True,order_OVGF1RjxmVnP7k,pay_OVGCgz3hyeVjM4,True,None,5,7,3
2024-07-07,45,Mubina Nahar,naharmustafa786@gmail.com,9116426352,402 Kondhwa,411048,2.0,True,order_OVgOAevt5329sy,pay_OVgLqn4Knl2vSZ,True,None,6,7,3
2024-07-07,46,Moiz Lalji,naharmustafa786@gmail.com,9116426352,abc,314001,1.0,True,order_OVoswwS41EKVpe,pay_OVoqdW74KAmwRu,True,None,6,7,3
2024-07-18,47,Huzaifa Mamji,naharmustafa7@gmail.com,9699596739,kondhwa pune,411048,1.0,True,order_Oa6Ulzhygu0jSa,pay_Oa6SSeU1cnEmqD,True,None,3,7,3
2024-07-18,52,Mustafa Nahar,mustafa.bohra20@vit.edu,9116426352,abc,411048,1.0,True,order_Oa7HU6FPMgnvzW,pay_Oa7H2UiveZrc4X,True,None,3,7,3
2024-07-18,51,Mustafa Nahar,mustafa.bohra20@vit.edu,9116426352,abc,314001,1.0,True,order_Oa7EWiuitLwVWj,pay_Oa7E5UMYwjpyA2,True,None,3,7,3
2024-07-18,53,suresh,naharmustafa786@gmail.com,9699596739,dungarpur,314001,5.0,True,order_Oa9PbNHL6AGLye,pay_Oa9P3TccyQtwik,True,None,3,7,3
2024-07-20,57,Mustafa testing,naharmustafa7@gmail.com,9699596739,abc kondhwa chowk,411048,7.0,True,order_OaoUUR7LglUD6V,pay_OaoSCyEDe2iCIr,False,None,5,7,3
2024-07-18,56,mustu,naharmustafa7@gmail.com,9699596739,abc,314001,9.0,True,order_OaBugOK95Axc32,pay_OaBsLBPdChRGgw,True,None,3,7,3
2024-07-18,55,Mubina Nahar Wala,naharmustafa7@gmail.com,9699596739,Dungarpur,314001,20.0,True,order_OaBqwoBs1UcNGz,pay_OaBodIGJem85Ee,True,None,3,7,3
2024-07-18,54,Mustafa Nahar 1,mustafa.bohra20@vit.edu,9116426352,abc,411048,1.0,True,order_Oa9ZSdIhsQF5o4,pay_Oa9Z5CvzTJEqIH,True,None,3,7,3

In [78]:
abc = df.resample('D').sum()['total_amount']
abc

created_at
2024-07-06     2.0
2024-07-07     3.0
2024-07-08     0.0
2024-07-09     0.0
2024-07-10     0.0
2024-07-11     0.0
2024-07-12     0.0
2024-07-13     0.0
2024-07-14     0.0
2024-07-15     0.0
2024-07-16     0.0
2024-07-17     0.0
2024-07-18    55.0
2024-07-19     0.0
2024-07-20    10.5
2024-07-21     0.0
2024-07-22     6.0
2024-07-23     1.0
Freq: D, Name: total_amount, dtype: float64

In [80]:
daily_sales = df.resample('D').sum()['total_amount']

# Creating a DataFrame for modeling
df_model = daily_sales.to_frame().reset_index()
df_model['day_of_week'] = df_model['created_at'].dt.dayofweek
df_model['month'] = df_model['created_at'].dt.month
df_model['quarter'] = df_model['created_at'].dt.quarter

df_model

   created_at  total_amount  day_of_week  month  quarter
0  2024-07-06           2.0            5      7        3
1  2024-07-07           3.0            6      7        3
2  2024-07-08           0.0            0      7        3
3  2024-07-09           0.0            1      7        3
4  2024-07-10           0.0            2      7        3
5  2024-07-11           0.0            3      7        3
6  2024-07-12           0.0            4      7        3
7  2024-07-13           0.0            5      7        3
8  2024-07-14           0.0            6      7        3
9  2024-07-15           0.0            0      7        3
10 2024-07-16           0.0            1      7        3
11 2024-07-17           0.0            2      7        3
12 2024-07-18          55.0            3      7        3
13 2024-07-19           0.0            4      7        3
14 2024-07-20          10.5            5      7        3
15 2024-07-21           0.0            6      7        3
16 2024-07-22           6.0            0      7        3
17 2024-07-23           1.0            1      7        3

In [90]:
from sklearn.model_selection import train_test_split

# Features and target variable
X = df_model.drop(columns=['created_at', 'total_amount'])
y = df_model['total_amount']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5000)

In [91]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Initialize and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

In [92]:
from sklearn.metrics import r2_score

# Calculate the R² score
r2 = r2_score(y_test, y_pred)

# Convert R² score to percentage
accuracy_percentage = r2 * 100

print(f'R² Score: {r2}')
print(f'Accuracy: {accuracy_percentage:.2f}%')

R² Score: 0.0
Accuracy: 0.00%

In [47]:
y_pred

array([4.55882353])

In [95]:
# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print(f'MAE: {mae}')
print(f'RMSE: {rmse}')

MAE: 5.509462151394422
RMSE: 5.509802661641542

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [96]:
# Predict future sales
future_dates = pd.date_range(start='2024-08-01', end='2024-08-30', freq='D')
future_df = pd.DataFrame(index=future_dates)

# Generate features for future dates
future_df['day_of_week'] = future_df.index.dayofweek
future_df['month'] = future_df.index.month
future_df['quarter'] = future_df.index.quarter

# Predict sales for future dates
future_sales = model.predict(future_df)
future_df['predicted_sales'] = future_sales

print(future_df)

            day_of_week  month  quarter  predicted_sales
2024-08-01            3      8        3         5.529880
2024-08-02            4      8        3         5.570717
2024-08-03            5      8        3         5.611554
2024-08-04            6      8        3         5.652390
2024-08-05            0      8        3         5.407371
2024-08-06            1      8        3         5.448207
2024-08-07            2      8        3         5.489044
2024-08-08            3      8        3         5.529880
2024-08-09            4      8        3         5.570717
2024-08-10            5      8        3         5.611554
2024-08-11            6      8        3         5.652390
2024-08-12            0      8        3         5.407371
2024-08-13            1      8        3         5.448207
2024-08-14            2      8        3         5.489044
2024-08-15            3      8        3         5.529880
2024-08-16            4      8        3         5.570717
2024-08-17            5      8        3         5.611554
2024-08-18            6      8        3         5.652390
2024-08-19            0      8        3         5.407371
2024-08-20            1      8        3         5.448207
2024-08-21            2      8        3         5.489044
2024-08-22            3      8        3         5.529880
2024-08-23            4      8        3         5.570717
2024-08-24            5      8        3         5.611554
2024-08-25            6      8        3         5.652390
2024-08-26            0      8        3         5.407371
2024-08-27            1      8        3         5.448207
2024-08-28            2      8        3         5.489044
2024-08-29            3      8        3         5.529880
2024-08-30            4      8        3         5.570717

In [97]:
df_model

   created_at  total_amount  day_of_week  month  quarter
0  2024-07-06           2.0            5      7        3
1  2024-07-07           3.0            6      7        3
2  2024-07-08           0.0            0      7        3
3  2024-07-09           0.0            1      7        3
4  2024-07-10           0.0            2      7        3
5  2024-07-11           0.0            3      7        3
6  2024-07-12           0.0            4      7        3
7  2024-07-13           0.0            5      7        3
8  2024-07-14           0.0            6      7        3
9  2024-07-15           0.0            0      7        3
10 2024-07-16           0.0            1      7        3
11 2024-07-17           0.0            2      7        3
12 2024-07-18          55.0            3      7        3
13 2024-07-19           0.0            4      7        3
14 2024-07-20          10.5            5      7        3
15 2024-07-21           0.0            6      7        3
16 2024-07-22           6.0            0      7        3
17 2024-07-23           1.0            1      7        3

In [99]:
query = 'SELECT * FROM mainapp_customers_order_from_website'  # Replace with your actual table name
df = pd.read_sql(query, engine)
df

# Preprocessing
df['created_at'] = pd.to_datetime(df['created_at'])  # Convert created_at column to datetime
df = df.set_index('created_at')

# Feature engineering
df['day_of_week'] = df.index.dayofweek
df['month'] = df.index.month
df['quarter'] = df.index.quarter

# Aggregating total sales by day
daily_sales = df.resample('D').sum()['total_amount']

# Creating a DataFrame for modeling
df_model = daily_sales.to_frame().reset_index()
df_model['day_of_week'] = df_model['created_at'].dt.dayofweek
df_model['month'] = df_model['created_at'].dt.month
df_model['quarter'] = df_model['created_at'].dt.quarter
df_model['lag_1'] = df_model['total_amount'].shift(1)
df_model['lag_7'] = df_model['total_amount'].shift(7)
df_model = df_model.dropna()

# Features and target variable
X = df_model.drop(columns=['created_at', 'total_amount'])
y = df_model['total_amount']

# Split the data with a fixed random_state for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [54]:
# Initialize and train the Linear Regression model
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Make predictions
lr_y_pred = lr_model.predict(X_test)

# Evaluate the model
lr_mae = mean_absolute_error(y_test, lr_y_pred)
lr_rmse = mean_squared_error(y_test, lr_y_pred, squared=False)
lr_r2 = r2_score(y_test, lr_y_pred)
lr_accuracy_percentage = lr_r2 * 100

print(f'Linear Regression MAE: {lr_mae}')
print(f'Linear Regression RMSE: {lr_rmse}')
print(f'Linear Regression R² Score: {lr_r2}')
print(f'Linear Regression Accuracy: {lr_accuracy_percentage:.2f}%')

Linear Regression MAE: 26.38844103912026
Linear Regression RMSE: 36.541354491485436
Linear Regression R² Score: -0.7656470586081361
Linear Regression Accuracy: -76.56%

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [58]:
import pandas as pd
from sqlalchemy import create_engine
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Define parameter grid
rf_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Initialize the model
rf_model = RandomForestRegressor(random_state=42)

# Initialize GridSearchCV
rf_grid_search = GridSearchCV(estimator=rf_model, param_grid=rf_param_grid, cv=3, n_jobs=-1, verbose=2)

# Fit the model
rf_grid_search.fit(X_train, y_train)

# Best parameters
print(rf_grid_search.best_params_)

# Make predictions with the best estimator
best_rf_model = rf_grid_search.best_estimator_
rf_y_pred = best_rf_model.predict(X_test)

# Evaluate the model
rf_mae = mean_absolute_error(y_test, rf_y_pred)
rf_rmse = mean_squared_error(y_test, rf_y_pred, squared=False)
rf_r2 = r2_score(y_test, rf_y_pred)
rf_accuracy_percentage = rf_r2 * 100

print(f'Random Forest MAE: {rf_mae}')
print(f'Random Forest RMSE: {rf_rmse}')
print(f'Random Forest R² Score: {rf_r2}')
print(f'Random Forest Accuracy: {rf_accuracy_percentage:.2f}%')

Fitting 3 folds for each of 108 candidates, totalling 324 fits
{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 100}
Random Forest MAE: 27.5
Random Forest RMSE: 37.4870942771733
Random Forest R² Score: -0.8582244460769306
Random Forest Accuracy: -85.82%

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [59]:
# Define parameter grid
xgb_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.7, 0.8, 1.0]
}

# Initialize the model
xgb_model = XGBRegressor(random_state=42)

# Initialize GridSearchCV
xgb_grid_search = GridSearchCV(estimator=xgb_model, param_grid=xgb_param_grid, cv=3, n_jobs=-1, verbose=2)

# Fit the model
xgb_grid_search.fit(X_train, y_train)

# Best parameters
print(xgb_grid_search.best_params_)

# Make predictions with the best estimator
best_xgb_model = xgb_grid_search.best_estimator_
xgb_y_pred = best_xgb_model.predict(X_test)

# Evaluate the model
xgb_mae = mean_absolute_error(y_test, xgb_y_pred)
xgb_rmse = mean_squared_error(y_test, xgb_y_pred, squared=False)
xgb_r2 = r2_score(y_test, xgb_y_pred)
xgb_accuracy_percentage = xgb_r2 * 100

print(f'XGBoost MAE: {xgb_mae}')
print(f'XGBoost RMSE: {xgb_rmse}')
print(f'XGBoost R² Score: {xgb_r2}')
print(f'XGBoost Accuracy: {xgb_accuracy_percentage:.2f}%')

Fitting 3 folds for each of 81 candidates, totalling 243 fits
{'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100, 'subsample': 0.7}
XGBoost MAE: 28.736705422401428
XGBoost RMSE: 37.85144296975342
XGBoost R² Score: -0.8945213023371841
XGBoost Accuracy: -89.45%

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(